nasa_mars_news = 'https://mars.nasa.gov/news/'
nasa_jpl = 'https://www.jpl.nasa.gov/spaceimages/?search=&category=Mars'
mars_twitter_page = 'https://twitter.com/marswxreport?lang=en'
executable_path = '/usr/local/bin/chromedriver'
browser_choice = 'chrome'
